### ISSUE TITLE
Lazy example should specify that `opts` isn't optional

### ISSUE THREAD

**Issue by adrian5** [utilyre/sentiment.nvim#10]
When using the config example from the README, but omitting the `opts` property (sticking to defaults), the plugin isn't initialized properly for me. Manually calling `require("sentiment").enable()` doesn't alleviate this.

Would be good to see this behavior changed, as I think it doesn't happen with other plugins.

If it cannot be changed, the README could point out that `opts` is mandatory, or that `config = true` must be set when `opts` isn't, to ensure `sentiment.setup()` is run.

**Comment by utilyre** [comment]
This is a lazy.nvim "issue" if you will.

**Comment by adrian5** [comment]
I can see how it would be a lazy.nvim issue. Still would prefer it to be documented, as I don't think having to leave an empty `opts = {}` is self evident. I have several other plugins without `opts` set.
